# Generated by scripts/gen_makefile_deps.tl
# Do not edit by hand

TL_FILES = src/cyan/cli.tl src/cyan/command.tl src/cyan/commands/build.tl src/cyan/commands/check-gen.tl src/cyan/commands/initialize.tl src/cyan/commands/run.tl src/cyan/commands/warnings.tl src/cyan/config.tl src/cyan/decoration.tl src/cyan/event.tl src/cyan/fs.tl src/cyan/graph.tl src/cyan/interaction.tl src/cyan/invocation-context.tl src/cyan/log.tl src/cyan/meta.tl src/cyan/sandbox.tl src/cyan/script.tl src/cyan/tlcommon.tl src/cyan/util.tl src/spec/api/config_spec.tl src/spec/api/decoration_spec.tl src/spec/api/graph_spec.tl src/spec/api/sandbox_spec.tl src/spec/api/script_spec.tl src/spec/api/util_spec.tl src/spec/commands/build_spec.tl src/spec/commands/check_spec.tl src/spec/commands/gen_spec.tl src/spec/commands/init_spec.tl src/spec/commands/no_script_spec.tl src/spec/commands/run_spec.tl src/spec/commands/warnings_spec.tl src/testing/batch-assertion.tl src/testing/command-runners.tl src/testing/finally.tl src/testing/temporary-files.tl
LUA_FILES = build/cyan/cli.lua build/cyan/command.lua build/cyan/commands/build.lua build/cyan/commands/check-gen.lua build/cyan/commands/initialize.lua build/cyan/commands/run.lua build/cyan/commands/warnings.lua build/cyan/config.lua build/cyan/decoration.lua build/cyan/event.lua build/cyan/fs.lua build/cyan/graph.lua build/cyan/interaction.lua build/cyan/invocation-context.lua build/cyan/log.lua build/cyan/meta.lua build/cyan/sandbox.lua build/cyan/script.lua build/cyan/tlcommon.lua build/cyan/util.lua build/spec/api/config_spec.lua build/spec/api/decoration_spec.lua build/spec/api/graph_spec.lua build/spec/api/sandbox_spec.lua build/spec/api/script_spec.lua build/spec/api/util_spec.lua build/spec/commands/build_spec.lua build/spec/commands/check_spec.lua build/spec/commands/gen_spec.lua build/spec/commands/init_spec.lua build/spec/commands/no_script_spec.lua build/spec/commands/run_spec.lua build/spec/commands/warnings_spec.lua build/testing/batch-assertion.lua build/testing/command-runners.lua build/testing/finally.lua build/testing/temporary-files.lua
build/cyan/cli.lua : src/cyan/cli.tl |  src/cyan/sandbox.tl src/cyan/log.tl src/cyan/decoration.tl src/cyan/commands/initialize.tl src/cyan/commands/check-gen.tl src/cyan/util.tl src/cyan/event.tl src/cyan/command.tl src/cyan/meta.tl src/cyan/commands/run.tl src/cyan/script.tl src/cyan/commands/warnings.tl src/cyan/fs.tl src/cyan/config.tl src/cyan/commands/build.tl src/cyan/tlcommon.tl src/cyan/invocation-context.tl src/cyan/graph.tl build_directories
build/cyan/command.lua : src/cyan/command.tl |  src/cyan/invocation-context.tl src/cyan/fs.tl src/cyan/config.tl src/cyan/sandbox.tl src/cyan/util.tl src/cyan/log.tl src/cyan/decoration.tl build_directories
build/cyan/commands/build.lua : src/cyan/commands/build.tl |  src/cyan/meta.tl src/cyan/script.tl src/cyan/config.tl src/cyan/log.tl src/cyan/decoration.tl src/cyan/sandbox.tl src/cyan/fs.tl src/cyan/graph.tl src/cyan/util.tl src/cyan/event.tl src/cyan/tlcommon.tl src/cyan/invocation-context.tl src/cyan/command.tl build_directories
build/cyan/commands/check-gen.lua : src/cyan/commands/check-gen.tl |  src/cyan/sandbox.tl src/cyan/log.tl src/cyan/decoration.tl src/cyan/fs.tl src/cyan/config.tl src/cyan/util.tl src/cyan/tlcommon.tl src/cyan/invocation-context.tl src/cyan/command.tl build_directories
build/cyan/commands/initialize.lua : src/cyan/commands/initialize.tl |  src/cyan/invocation-context.tl src/cyan/fs.tl src/cyan/sandbox.tl src/cyan/config.tl src/cyan/command.tl src/cyan/util.tl src/cyan/log.tl src/cyan/decoration.tl build_directories
build/cyan/commands/run.lua : src/cyan/commands/run.tl |  src/cyan/sandbox.tl src/cyan/log.tl src/cyan/decoration.tl src/cyan/fs.tl src/cyan/config.tl src/cyan/util.tl src/cyan/tlcommon.tl src/cyan/invocation-context.tl src/cyan/command.tl build_directories
build/cyan/commands/warnings.lua : src/cyan/commands/warnings.tl |  src/cyan/invocation-context.tl src/cyan/fs.tl src/cyan/sandbox.tl src/cyan/config.tl src/cyan/command.tl src/cyan/util.tl src/cyan/log.tl src/cyan/decoration.tl build_directories
build/cyan/config.lua : src/cyan/config.tl |  src/cyan/fs.tl src/cyan/util.tl src/cyan/sandbox.tl build_directories
build/cyan/decoration.lua : src/cyan/decoration.tl |  src/cyan/util.tl build_directories
build/cyan/event.lua : src/cyan/event.tl |  src/cyan/util.tl src/cyan/log.tl src/cyan/decoration.tl build_directories
build/cyan/fs.lua : src/cyan/fs.tl |  src/cyan/util.tl build_directories
build/cyan/graph.lua : src/cyan/graph.tl |  src/cyan/util.tl src/cyan/fs.tl src/cyan/config.tl src/cyan/sandbox.tl src/cyan/tlcommon.tl src/cyan/log.tl src/cyan/decoration.tl build_directories
build/cyan/interaction.lua : src/cyan/interaction.tl |  src/cyan/util.tl src/cyan/log.tl src/cyan/decoration.tl build_directories
build/cyan/invocation-context.lua : src/cyan/invocation-context.tl |  build_directories
build/cyan/log.lua : src/cyan/log.tl |  src/cyan/util.tl src/cyan/decoration.tl build_directories
build/cyan/meta.lua : src/cyan/meta.tl |  build_directories
build/cyan/sandbox.lua : src/cyan/sandbox.tl |  build_directories
build/cyan/script.lua : src/cyan/script.tl |  src/cyan/meta.tl src/cyan/log.tl src/cyan/decoration.tl src/cyan/config.tl src/cyan/util.tl src/cyan/fs.tl src/cyan/sandbox.tl src/cyan/invocation-context.tl src/cyan/command.tl build_directories
build/cyan/tlcommon.lua : src/cyan/tlcommon.tl |  src/cyan/fs.tl src/cyan/config.tl src/cyan/sandbox.tl src/cyan/util.tl src/cyan/log.tl src/cyan/decoration.tl build_directories
build/cyan/util.lua : src/cyan/util.tl |  build_directories
build/spec/api/config_spec.lua : src/spec/api/config_spec.tl |  src/cyan/fs.tl src/cyan/util.tl src/cyan/sandbox.tl src/cyan/config.tl build_directories
build/spec/api/decoration_spec.lua : src/spec/api/decoration_spec.tl |  src/cyan/util.tl src/cyan/decoration.tl build_directories
build/spec/api/graph_spec.lua : src/spec/api/graph_spec.tl |  src/cyan/sandbox.tl src/cyan/log.tl src/cyan/decoration.tl src/cyan/fs.tl src/testing/finally.tl src/cyan/util.tl src/cyan/graph.tl src/cyan/tlcommon.tl src/testing/temporary-files.tl src/cyan/config.tl build_directories
build/spec/api/sandbox_spec.lua : src/spec/api/sandbox_spec.tl |  src/cyan/sandbox.tl build_directories
build/spec/api/script_spec.lua : src/spec/api/script_spec.tl |  src/cyan/meta.tl src/cyan/script.tl src/cyan/log.tl src/cyan/decoration.tl src/cyan/invocation-context.tl src/cyan/fs.tl src/testing/finally.tl src/cyan/util.tl src/cyan/config.tl src/cyan/sandbox.tl src/testing/temporary-files.tl src/cyan/command.tl build_directories
build/spec/api/util_spec.lua : src/spec/api/util_spec.tl |  src/cyan/util.tl build_directories
build/spec/commands/build_spec.lua : src/spec/commands/build_spec.tl |  src/testing/finally.tl src/cyan/util.tl src/testing/command-runners.tl src/testing/temporary-files.tl src/testing/batch-assertion.tl build_directories
build/spec/commands/check_spec.lua : src/spec/commands/check_spec.tl |  src/testing/finally.tl src/cyan/util.tl src/testing/command-runners.tl src/testing/temporary-files.tl src/testing/batch-assertion.tl build_directories
build/spec/commands/gen_spec.lua : src/spec/commands/gen_spec.tl |  src/testing/finally.tl src/cyan/util.tl src/testing/command-runners.tl src/testing/temporary-files.tl src/testing/batch-assertion.tl build_directories
build/spec/commands/init_spec.lua : src/spec/commands/init_spec.tl |  src/testing/finally.tl src/cyan/util.tl src/testing/command-runners.tl src/testing/temporary-files.tl src/testing/batch-assertion.tl build_directories
build/spec/commands/no_script_spec.lua : src/spec/commands/no_script_spec.tl |  src/testing/command-runners.tl build_directories
build/spec/commands/run_spec.lua : src/spec/commands/run_spec.tl |  src/testing/finally.tl src/cyan/util.tl src/testing/command-runners.tl src/testing/temporary-files.tl src/testing/batch-assertion.tl build_directories
build/spec/commands/warnings_spec.lua : src/spec/commands/warnings_spec.tl |  src/testing/finally.tl src/cyan/util.tl src/testing/command-runners.tl src/testing/temporary-files.tl src/testing/batch-assertion.tl build_directories
build/testing/batch-assertion.lua : src/testing/batch-assertion.tl |  build_directories
build/testing/command-runners.lua : src/testing/command-runners.tl |  src/testing/finally.tl src/testing/batch-assertion.tl src/testing/temporary-files.tl src/cyan/util.tl build_directories
build/testing/finally.lua : src/testing/finally.tl |  src/cyan/util.tl build_directories
build/testing/temporary-files.lua : src/testing/temporary-files.tl |  src/testing/finally.tl src/cyan/util.tl build_directories
build_directories :
	@mkdir -p build
	@mkdir -p build/spec
	@mkdir -p build/cyan
	@mkdir -p build/testing
	@mkdir -p build/spec/api
	@mkdir -p build/spec/commands
	@mkdir -p build/cyan/commands
.PHONY: build_directories