# Generated by scripts/gen_makefile_deps.tl
# Do not edit by hand

TL_FILES = cyan/cli.tl cyan/command.tl cyan/commands/build.tl cyan/commands/check-gen.tl cyan/commands/export.tl cyan/commands/initialize.tl cyan/commands/run.tl cyan/commands/warnings.tl cyan/config.tl cyan/decoration.tl cyan/fs.tl cyan/graph.tl cyan/interaction.tl cyan/invocation-context.tl cyan/log.tl cyan/meta.tl cyan/sandbox.tl cyan/script.tl cyan/tlcommon.tl cyan/util.tl spec/api/config_spec.tl spec/api/decoration_spec.tl spec/api/graph_spec.tl spec/api/sandbox_spec.tl spec/api/script_spec.tl spec/api/util_spec.tl spec/commands/build_spec.tl spec/commands/check_spec.tl spec/commands/gen_spec.tl spec/commands/init_spec.tl spec/commands/no_script_spec.tl spec/commands/run_spec.tl spec/commands/warnings_spec.tl testing/batch-assertion.tl testing/command-runners.tl testing/finally.tl testing/temporary-files.tl
LUA_FILES = build/../cyan/cli.lua build/../cyan/command.lua build/../cyan/commands/build.lua build/../cyan/commands/check-gen.lua build/../cyan/commands/export.lua build/../cyan/commands/initialize.lua build/../cyan/commands/run.lua build/../cyan/commands/warnings.lua build/../cyan/config.lua build/../cyan/decoration.lua build/../cyan/fs.lua build/../cyan/graph.lua build/../cyan/interaction.lua build/../cyan/invocation-context.lua build/../cyan/log.lua build/../cyan/meta.lua build/../cyan/sandbox.lua build/../cyan/script.lua build/../cyan/tlcommon.lua build/../cyan/util.lua build/../spec/api/config_spec.lua build/../spec/api/decoration_spec.lua build/../spec/api/graph_spec.lua build/../spec/api/sandbox_spec.lua build/../spec/api/script_spec.lua build/../spec/api/util_spec.lua build/../spec/commands/build_spec.lua build/../spec/commands/check_spec.lua build/../spec/commands/gen_spec.lua build/../spec/commands/init_spec.lua build/../spec/commands/no_script_spec.lua build/../spec/commands/run_spec.lua build/../spec/commands/warnings_spec.lua build/../testing/batch-assertion.lua build/../testing/command-runners.lua build/../testing/finally.lua build/../testing/temporary-files.lua
CHECKS = build/../cyan/cli.lua.checked build/../cyan/command.lua.checked build/../cyan/commands/build.lua.checked build/../cyan/commands/check-gen.lua.checked build/../cyan/commands/export.lua.checked build/../cyan/commands/initialize.lua.checked build/../cyan/commands/run.lua.checked build/../cyan/commands/warnings.lua.checked build/../cyan/config.lua.checked build/../cyan/decoration.lua.checked build/../cyan/fs.lua.checked build/../cyan/graph.lua.checked build/../cyan/interaction.lua.checked build/../cyan/invocation-context.lua.checked build/../cyan/log.lua.checked build/../cyan/meta.lua.checked build/../cyan/sandbox.lua.checked build/../cyan/script.lua.checked build/../cyan/tlcommon.lua.checked build/../cyan/util.lua.checked build/../spec/api/config_spec.lua.checked build/../spec/api/decoration_spec.lua.checked build/../spec/api/graph_spec.lua.checked build/../spec/api/sandbox_spec.lua.checked build/../spec/api/script_spec.lua.checked build/../spec/api/util_spec.lua.checked build/../spec/commands/build_spec.lua.checked build/../spec/commands/check_spec.lua.checked build/../spec/commands/gen_spec.lua.checked build/../spec/commands/init_spec.lua.checked build/../spec/commands/no_script_spec.lua.checked build/../spec/commands/run_spec.lua.checked build/../spec/commands/warnings_spec.lua.checked build/../testing/batch-assertion.lua.checked build/../testing/command-runners.lua.checked build/../testing/finally.lua.checked build/../testing/temporary-files.lua.checked
build/../cyan/cli.lua.checked : cyan/cli.tl | build_directories
build/../cyan/cli.lua : cyan/cli.tl | build_directories
build/../cyan/command.lua.checked : cyan/command.tl | build_directories
build/../cyan/command.lua : cyan/command.tl | build_directories
build/../cyan/commands/build.lua.checked : cyan/commands/build.tl | build_directories
build/../cyan/commands/build.lua : cyan/commands/build.tl | build_directories
build/../cyan/commands/check-gen.lua.checked : cyan/commands/check-gen.tl | build_directories
build/../cyan/commands/check-gen.lua : cyan/commands/check-gen.tl | build_directories
build/../cyan/commands/export.lua.checked : cyan/commands/export.tl | build_directories
build/../cyan/commands/export.lua : cyan/commands/export.tl | build_directories
build/../cyan/commands/initialize.lua.checked : cyan/commands/initialize.tl | build_directories
build/../cyan/commands/initialize.lua : cyan/commands/initialize.tl | build_directories
build/../cyan/commands/run.lua.checked : cyan/commands/run.tl | build_directories
build/../cyan/commands/run.lua : cyan/commands/run.tl | build_directories
build/../cyan/commands/warnings.lua.checked : cyan/commands/warnings.tl | build_directories
build/../cyan/commands/warnings.lua : cyan/commands/warnings.tl | build_directories
build/../cyan/config.lua.checked : cyan/config.tl | build_directories
build/../cyan/config.lua : cyan/config.tl | build_directories
build/../cyan/decoration.lua.checked : cyan/decoration.tl | build_directories
build/../cyan/decoration.lua : cyan/decoration.tl | build_directories
build/../cyan/fs.lua.checked : cyan/fs.tl | build_directories
build/../cyan/fs.lua : cyan/fs.tl | build_directories
build/../cyan/graph.lua.checked : cyan/graph.tl | build_directories
build/../cyan/graph.lua : cyan/graph.tl | build_directories
build/../cyan/interaction.lua.checked : cyan/interaction.tl | build_directories
build/../cyan/interaction.lua : cyan/interaction.tl | build_directories
build/../cyan/invocation-context.lua.checked : cyan/invocation-context.tl | build_directories
build/../cyan/invocation-context.lua : cyan/invocation-context.tl | build_directories
build/../cyan/log.lua.checked : cyan/log.tl | build_directories
build/../cyan/log.lua : cyan/log.tl | build_directories
build/../cyan/meta.lua.checked : cyan/meta.tl | build_directories
build/../cyan/meta.lua : cyan/meta.tl | build_directories
build/../cyan/sandbox.lua.checked : cyan/sandbox.tl | build_directories
build/../cyan/sandbox.lua : cyan/sandbox.tl | build_directories
build/../cyan/script.lua.checked : cyan/script.tl | build_directories
build/../cyan/script.lua : cyan/script.tl | build_directories
build/../cyan/tlcommon.lua.checked : cyan/tlcommon.tl | build_directories
build/../cyan/tlcommon.lua : cyan/tlcommon.tl | build_directories
build/../cyan/util.lua.checked : cyan/util.tl | build_directories
build/../cyan/util.lua : cyan/util.tl | build_directories
build/../spec/api/config_spec.lua.checked : spec/api/config_spec.tl | build_directories
build/../spec/api/config_spec.lua : spec/api/config_spec.tl | build_directories
build/../spec/api/decoration_spec.lua.checked : spec/api/decoration_spec.tl | build_directories
build/../spec/api/decoration_spec.lua : spec/api/decoration_spec.tl | build_directories
build/../spec/api/graph_spec.lua.checked : spec/api/graph_spec.tl | build_directories
build/../spec/api/graph_spec.lua : spec/api/graph_spec.tl | build_directories
build/../spec/api/sandbox_spec.lua.checked : spec/api/sandbox_spec.tl | build_directories
build/../spec/api/sandbox_spec.lua : spec/api/sandbox_spec.tl | build_directories
build/../spec/api/script_spec.lua.checked : spec/api/script_spec.tl | build_directories
build/../spec/api/script_spec.lua : spec/api/script_spec.tl | build_directories
build/../spec/api/util_spec.lua.checked : spec/api/util_spec.tl | build_directories
build/../spec/api/util_spec.lua : spec/api/util_spec.tl | build_directories
build/../spec/commands/build_spec.lua.checked : spec/commands/build_spec.tl | build_directories
build/../spec/commands/build_spec.lua : spec/commands/build_spec.tl | build_directories
build/../spec/commands/check_spec.lua.checked : spec/commands/check_spec.tl | build_directories
build/../spec/commands/check_spec.lua : spec/commands/check_spec.tl | build_directories
build/../spec/commands/gen_spec.lua.checked : spec/commands/gen_spec.tl | build_directories
build/../spec/commands/gen_spec.lua : spec/commands/gen_spec.tl | build_directories
build/../spec/commands/init_spec.lua.checked : spec/commands/init_spec.tl | build_directories
build/../spec/commands/init_spec.lua : spec/commands/init_spec.tl | build_directories
build/../spec/commands/no_script_spec.lua.checked : spec/commands/no_script_spec.tl | build_directories
build/../spec/commands/no_script_spec.lua : spec/commands/no_script_spec.tl | build_directories
build/../spec/commands/run_spec.lua.checked : spec/commands/run_spec.tl | build_directories
build/../spec/commands/run_spec.lua : spec/commands/run_spec.tl | build_directories
build/../spec/commands/warnings_spec.lua.checked : spec/commands/warnings_spec.tl | build_directories
build/../spec/commands/warnings_spec.lua : spec/commands/warnings_spec.tl | build_directories
build/../testing/batch-assertion.lua.checked : testing/batch-assertion.tl | build_directories
build/../testing/batch-assertion.lua : testing/batch-assertion.tl | build_directories
build/../testing/command-runners.lua.checked : testing/command-runners.tl | build_directories
build/../testing/command-runners.lua : testing/command-runners.tl | build_directories
build/../testing/finally.lua.checked : testing/finally.tl | build_directories
build/../testing/finally.lua : testing/finally.tl | build_directories
build/../testing/temporary-files.lua.checked : testing/temporary-files.tl | build_directories
build/../testing/temporary-files.lua : testing/temporary-files.tl | build_directories
build_directories :
	@mkdir -p build
	@mkdir -p build/..
	@mkdir -p build/../cyan
	@mkdir -p build/../spec
	@mkdir -p build/../testing
	@mkdir -p build/../spec/api
	@mkdir -p build/../spec/commands
	@mkdir -p build/../cyan/commands
.PHONY: build_directories